"""estado-luna

Revision ID: 03c321f18c52
Revises: b81f232120c1
Create Date: 2020-01-20 21:48:08.086245

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '03c321f18c52'
down_revision = 'b81f232120c1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('luna', sa.Column('estado', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('luna', 'estado')
    # ### end Alembic commands ###
