"""sensor suelo4

Revision ID: 1b34700f572d
Revises: 85f8bb870a63
Create Date: 2019-11-13 01:10:50.234720

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1b34700f572d'
down_revision = '85f8bb870a63'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sensorhumsuelostream', sa.Column('hum_suelo', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sensorhumsuelostream', 'hum_suelo')
    # ### end Alembic commands ###
