"""config inicio

Revision ID: 272d87762b00
Revises: 3453230c1e15
Create Date: 2019-11-23 23:23:42.347502

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '272d87762b00'
down_revision = '3453230c1e15'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('configuracion', sa.Column('inicio', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('configuracion', 'inicio')
    # ### end Alembic commands ###
