"""configuracion humedad_suelo

Revision ID: 3453230c1e15
Revises: 1b34700f572d
Create Date: 2019-11-13 22:52:11.717582

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3453230c1e15'
down_revision = '1b34700f572d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('configuracion', sa.Column('humedad_suelo', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('configuracion', 'humedad_suelo')
    # ### end Alembic commands ###
