"""ph float

Revision ID: 37c407a00a45
Revises: c5a112840e9e
Create Date: 2019-10-09 02:01:30.613465

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '37c407a00a45'
down_revision = 'c5a112840e9e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('configuracion', 'ph_max')
    op.drop_column('configuracion', 'ph_min')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('configuracion', sa.Column('ph_min', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('configuracion', sa.Column('ph_max', sa.INTEGER(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
