"""ph integer capo2

Revision ID: 3f4ec3347e31
Revises: 0d139784444d
Create Date: 2019-10-09 02:56:47.215441

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3f4ec3347e31'
down_revision = '0d139784444d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('configuracion', sa.Column('ph_max', sa.Integer(), nullable=True))
    op.add_column('configuracion', sa.Column('ph_min', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('configuracion', 'ph_min')
    op.drop_column('configuracion', 'ph_max')
    # ### end Alembic commands ###
