"""tabla sensorstream

Revision ID: 4a982aba4f81
Revises: 6b8cbe9e92b8
Create Date: 2019-09-05 18:30:46.490070

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4a982aba4f81'
down_revision = '6b8cbe9e92b8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sensorstream',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fecha', sa.String(), nullable=True),
    sa.Column('hora', sa.String(), nullable=True),
    sa.Column('temp', sa.String(), nullable=True),
    sa.Column('hum', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sensorstream')
    # ### end Alembic commands ###
