"""moon-rise-set

Revision ID: 4f450104fb4f
Revises: 66422326e0ca
Create Date: 2020-01-20 01:50:39.816913

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4f450104fb4f'
down_revision = '66422326e0ca'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('luna', sa.Column('moon_rise', sa.String(), nullable=True))
    op.add_column('luna', sa.Column('moon_set', sa.String(), nullable=True))
    op.drop_column('luna', 'hora')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('luna', sa.Column('hora', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('luna', 'moon_set')
    op.drop_column('luna', 'moon_rise')
    # ### end Alembic commands ###
