"""modificacion tabla configuracion

Revision ID: 4f59d0943413
Revises: ae5a5b709448
Create Date: 2019-08-20 21:38:07.746593

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4f59d0943413'
down_revision = 'ae5a5b709448'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('configuracion', sa.Column('nombre_conf', sa.String(), nullable=True))
    op.create_unique_constraint(None, 'configuracion', ['nombre_conf'])
    op.drop_column('configuracion', 'pid')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('configuracion', sa.Column('pid', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'configuracion', type_='unique')
    op.drop_column('configuracion', 'nombre_conf')
    # ### end Alembic commands ###
