"""sensor luz

Revision ID: 543540a8684d
Revises: b732b832ccbd
Create Date: 2019-10-30 15:18:00.860226

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '543540a8684d'
down_revision = 'b732b832ccbd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sensorLuzstream',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fecha', sa.String(), nullable=True),
    sa.Column('hora', sa.String(), nullable=True),
    sa.Column('luz', sa.Integer(), nullable=True),
    sa.Column('sol', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sensorluz',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('fecha', sa.String(), nullable=True),
    sa.Column('hora', sa.String(), nullable=True),
    sa.Column('luz', sa.Integer(), nullable=True),
    sa.Column('sol', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sensorluz')
    op.drop_table('sensorLuzstream')
    # ### end Alembic commands ###
