"""agregamos extractor

Revision ID: 6077356b7e8a
Revises: 536332199c33
Create Date: 2019-08-23 20:06:22.784836

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6077356b7e8a'
down_revision = '536332199c33'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('configuracion', sa.Column('extractor', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('configuracion', 'extractor')
    # ### end Alembic commands ###
