"""agregamos todo luna y tb imagen

Revision ID: 62742d235ea2
Revises: 0f83f5dfaaaa
Create Date: 2019-08-28 23:59:04.572806

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '62742d235ea2'
down_revision = '0f83f5dfaaaa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('luna', sa.Column('image', sa.LargeBinary(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('luna', 'image')
    # ### end Alembic commands ###
