"""config23

Revision ID: 62b899d25f47
Revises: 803fd79ea0b1
Create Date: 2019-11-23 23:46:03.380162

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '62b899d25f47'
down_revision = '803fd79ea0b1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('configuracion', sa.Column('inicio', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('configuracion', 'inicio')
    # ### end Alembic commands ###
