"""ph string

Revision ID: 62d2ba652bc8
Revises: c557c08b9066
Create Date: 2019-10-08 19:33:44.028455

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '62d2ba652bc8'
down_revision = 'c557c08b9066'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sensorph', 'ph')
    op.drop_column('sensorphstream', 'ph')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sensorphstream', sa.Column('ph', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('sensorph', sa.Column('ph', sa.INTEGER(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
