"""hemisferio

Revision ID: 66422326e0ca
Revises: ab02f1e54e57
Create Date: 2020-01-17 21:41:30.030155

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '66422326e0ca'
down_revision = 'ab02f1e54e57'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('luna', sa.Column('hemisferio', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('luna', 'hemisferio')
    # ### end Alembic commands ###
