"""tabla sensordht22

Revision ID: 6b8cbe9e92b8
Revises: b3984b15eb6e
Create Date: 2019-09-02 23:43:29.168781

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6b8cbe9e92b8'
down_revision = 'b3984b15eb6e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sensordht22',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('fecha', sa.String(), nullable=True),
    sa.Column('hora', sa.String(), nullable=True),
    sa.Column('temp', sa.Integer(), nullable=True),
    sa.Column('hum', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sensordht22')
    # ### end Alembic commands ###
