"""agregamos ventilador

Revision ID: 7166db3f5e45
Revises: ced14cdb12af
Create Date: 2019-09-17 15:59:17.800785

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7166db3f5e45'
down_revision = 'ced14cdb12af'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('configuracion', sa.Column('cantidad_ventilador', sa.Integer(), nullable=True))
    op.add_column('configuracion', sa.Column('ventilador', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('configuracion', 'ventilador')
    op.drop_column('configuracion', 'cantidad_ventilador')
    # ### end Alembic commands ###
