"""ph float

Revision ID: 7381b8be71ed
Revises: 37c407a00a45
Create Date: 2019-10-09 02:01:52.976727

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7381b8be71ed'
down_revision = '37c407a00a45'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('configuracion', sa.Column('ph_max', sa.Float(), nullable=True))
    op.add_column('configuracion', sa.Column('ph_min', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('configuracion', 'ph_min')
    op.drop_column('configuracion', 'ph_max')
    # ### end Alembic commands ###
