"""tabla sensorstream integer

Revision ID: 797b26533314
Revises: bfbbf9a2804e
Create Date: 2019-09-05 18:38:09.637225

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '797b26533314'
down_revision = 'bfbbf9a2804e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sensorstream', sa.Column('hum', sa.Integer(), nullable=True))
    op.add_column('sensorstream', sa.Column('temp', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sensorstream', 'temp')
    op.drop_column('sensorstream', 'hum')
    # ### end Alembic commands ###
