"""ph float

Revision ID: 7fffa37f5ee5
Revises: 57c08e4aeb85
Create Date: 2019-10-09 02:36:03.721190

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7fffa37f5ee5'
down_revision = '57c08e4aeb85'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('configuracion', sa.Column('ph_max', sa.Float(), nullable=True))
    op.add_column('configuracion', sa.Column('ph_min', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('configuracion', 'ph_min')
    op.drop_column('configuracion', 'ph_max')
    # ### end Alembic commands ###
