"""sensor suelo3

Revision ID: 85f8bb870a63
Revises: c25be567fd6f
Create Date: 2019-11-13 01:10:21.959233

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '85f8bb870a63'
down_revision = 'c25be567fd6f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sensorhumsuelostream', 'hum_suelo')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sensorhumsuelostream', sa.Column('hum_suelo', sa.INTEGER(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
