"""mensajes

Revision ID: 9e4eacd22f3b
Revises: 797b26533314
Create Date: 2019-09-14 21:23:08.861178

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9e4eacd22f3b'
down_revision = '797b26533314'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mensajes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fecha', sa.String(), nullable=True),
    sa.Column('hora', sa.String(), nullable=True),
    sa.Column('asunto', sa.String(), nullable=True),
    sa.Column('mensaje', sa.String(), nullable=True),
    sa.Column('numero_serie_rpi', sa.String(), nullable=True),
    sa.Column('ip_rpi', sa.String(), nullable=True),
    sa.Column('usuario', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('mensajes')
    # ### end Alembic commands ###
