"""tipo_cultivo

Revision ID: ab02f1e54e57
Revises: 4ec12bc020c6
Create Date: 2019-12-23 03:09:57.839831

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ab02f1e54e57'
down_revision = '4ec12bc020c6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('configuracion', sa.Column('tipo_cultivo', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('configuracion', 'tipo_cultivo')
    # ### end Alembic commands ###
