"""sensores big data

Revision ID: ab7e3efde613
Revises: d15a5101b5d2
Create Date: 2019-10-30 16:48:17.761736

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ab7e3efde613'
down_revision = 'd15a5101b5d2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sensorphbigdata',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('fecha', sa.String(), nullable=True),
    sa.Column('hora', sa.String(), nullable=True),
    sa.Column('ph', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('sensorluz', sa.Column('intensidad_sol', sa.Float(), nullable=True))
    op.drop_column('sensorluz', 'luz')
    op.drop_column('sensorluz', 'sol')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sensorluz', sa.Column('sol', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('sensorluz', sa.Column('luz', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('sensorluz', 'intensidad_sol')
    op.drop_table('sensorphbigdata')
    # ### end Alembic commands ###
