"""vamo

Revision ID: ae5a5b709448
Revises: 77190eba98d9
Create Date: 2019-08-20 01:45:17.416052

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ae5a5b709448'
down_revision = '77190eba98d9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('configuracion',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('luz', sa.Integer(), nullable=True),
    sa.Column('riego', sa.Integer(), nullable=True),
    sa.Column('humedad', sa.Integer(), nullable=True),
    sa.Column('ventilacion', sa.Integer(), nullable=True),
    sa.Column('temperatura', sa.Integer(), nullable=True),
    sa.Column('pid', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('configuracion')
    # ### end Alembic commands ###
