"""agregamos todo luna y tb imagen y recomendacion

Revision ID: b3984b15eb6e
Revises: 62742d235ea2
Create Date: 2019-08-29 00:26:33.188073

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b3984b15eb6e'
down_revision = '62742d235ea2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('luna', sa.Column('recomendacion', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('luna', 'recomendacion')
    # ### end Alembic commands ###
