"""ph integer capo4

Revision ID: b732b832ccbd
Revises: 25df80696629
Create Date: 2019-10-09 03:02:17.896037

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b732b832ccbd'
down_revision = '25df80696629'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('configuracion', sa.Column('ph_max', sa.Float(), nullable=True))
    op.add_column('configuracion', sa.Column('ph_min', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('configuracion', 'ph_min')
    op.drop_column('configuracion', 'ph_max')
    # ### end Alembic commands ###
