"""moon-rise-set-visibilidad

Revision ID: b81f232120c1
Revises: 4f450104fb4f
Create Date: 2020-01-20 02:09:43.294154

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b81f232120c1'
down_revision = '4f450104fb4f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('luna', sa.Column('visibilidad', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('luna', 'visibilidad')
    # ### end Alembic commands ###
