"""tabla sensorstream integer

Revision ID: bfbbf9a2804e
Revises: 4a982aba4f81
Create Date: 2019-09-05 18:37:56.190802

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bfbbf9a2804e'
down_revision = '4a982aba4f81'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sensorstream', 'temp')
    op.drop_column('sensorstream', 'hum')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sensorstream', sa.Column('hum', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('sensorstream', sa.Column('temp', sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
