"""ph float

Revision ID: c5a112840e9e
Revises: 62d2ba652bc8
Create Date: 2019-10-08 19:34:22.218070

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c5a112840e9e'
down_revision = '62d2ba652bc8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sensorph', sa.Column('ph', sa.Float(), nullable=True))
    op.add_column('sensorphstream', sa.Column('ph', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sensorphstream', 'ph')
    op.drop_column('sensorph', 'ph')
    # ### end Alembic commands ###
