"""respuesta

Revision ID: ced14cdb12af
Revises: fe75074ef9ce
Create Date: 2019-09-15 20:22:17.526432

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ced14cdb12af'
down_revision = 'fe75074ef9ce'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('mensajes', sa.Column('respuesta', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('mensajes', 'respuesta')
    # ### end Alembic commands ###
