"""sensor luz2

Revision ID: d15a5101b5d2
Revises: 543540a8684d
Create Date: 2019-10-30 15:52:47.197071

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd15a5101b5d2'
down_revision = '543540a8684d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sensorluzstream',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fecha', sa.String(), nullable=True),
    sa.Column('hora', sa.String(), nullable=True),
    sa.Column('luz', sa.Integer(), nullable=True),
    sa.Column('sol', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('sensorLuzstream')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sensorLuzstream',
    sa.Column('id', sa.INTEGER(), server_default=sa.text('nextval(\'"sensorLuzstream_id_seq"\'::regclass)'), autoincrement=True, nullable=False),
    sa.Column('fecha', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('hora', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('luz', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('sol', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='sensorLuzstream_pkey')
    )
    op.drop_table('sensorluzstream')
    # ### end Alembic commands ###
