"""sacamos extractor e intractor

Revision ID: f456866134ff
Revises: 4408fc0e153f
Create Date: 2019-08-28 02:32:52.642072

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f456866134ff'
down_revision = '4408fc0e153f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('configuracion', 'extractor')
    op.drop_column('configuracion', 'ventilacion')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('configuracion', sa.Column('ventilacion', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('configuracion', sa.Column('extractor', sa.INTEGER(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
