"""config23224

Revision ID: f51e560bf5fe
Revises: d0611f6f1828
Create Date: 2019-11-24 00:07:56.223715

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f51e560bf5fe'
down_revision = 'd0611f6f1828'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('configuracion', sa.Column('inicio', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('configuracion', 'inicio')
    # ### end Alembic commands ###
