"""id_mensaje

Revision ID: fe75074ef9ce
Revises: 9e4eacd22f3b
Create Date: 2019-09-15 06:28:17.093067

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fe75074ef9ce'
down_revision = '9e4eacd22f3b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('mensajes', sa.Column('id_mensaje', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('mensajes', 'id_mensaje')
    # ### end Alembic commands ###
